# Set the base image
FROM node:20.9.0 as build-stage

# Set the working directory
WORKDIR /app

# Copy project files and install dependencies
COPY package*.json ./
RUN npm install

COPY . .

# Build the application for production
RUN npm run build -- --configuration production

# Execution stage
FROM nginx:alpine
COPY --from=build-stage /app/dist/frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
